name: Build and push Docker image
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_AUTH_JSON: ${{ secrets.GOOGLE_AUTH_JSON }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and push
        run: ./build_and_push.sh "$(git rev-parse --short HEAD)"
